### PR TITLE
Using ktlint

### PR DESCRIPTION
**Pull request by oxtoacart**
- [x] Do the tests pass? Consistently?
- [ ] Did this change improve test coverage?
- [ ] Has it been reviewed/approved by relevant teammates?
- [ ] Can it be QA’d in staging or something like staging?
- [x] Is the code in question being linted? If not, consider adding a linter step to CI. If yes, make sure the linter is happy.
- [x] Do we know how we’re going to deploy this?
- [x] Are we clear on what the support and maintenance impact is?
- [x] Did you create new documentation? Is it accessible and in the right place?
- [ ] Has existing documentation been updated?
- [ ] Have you logged tickets for related technical debt with the label “techdebt”?

### CODE REVIEW

**Comment by oxtoacart** [comment]
Note - the actual kotlin code is unchanged, just uses the new formatting.

**Review by cosmicespresso — COMMENTED** [review]
The command line version of this looks like is working. When I intentionally mess up the formatting and then run `./gradlew ktlintCheck` I get errors like this:
```
> Task :db:ktlintMainSourceSetCheck FAILED
/Users/kallirroi/Documents/code/lantern/android/db-android/db/src/main/java/io/lantern/db/DB.kt:661:1 Unexpected indentation (124) (should be 8)
```
and with `./gradlew ktlintFormat` the file's formatting is fixed 👍 

However, if I just commit without running the above, the file remains unformatted. I'm using this Kotlin plugin for VSCode: https://github.com/fwcd/vscode-kotlin which does support linting.

When I open the project in my Android Studio, I can see intellisense (advantage over VSCode) but it still lets me commit without complaining.
Screen Shot 2021-04-23 at 10 45 30 AM

**Comment by oxtoacart** [comment]
Thanks @Kallirroi ! Can you try installing the git commit hook with `./gradlew addKtlintCheckGitPreCommitHook`?

**Comment by cosmicespresso** [comment]
> Thanks @Kallirroi ! Can you try installing the git commit hook with `./gradlew addKtlintCheckGitPreCommitHook`?

Great, now it complains 😄

**Comment by oxtoacart** [comment]
> > Thanks @Kallirroi ! Can you try installing the git commit hook with `./gradlew addKtlintCheckGitPreCommitHook`?
> 
> Great, now it complains 😄

Cool, I'll add a comment about enabling this.

**Comment by oxtoacart** [comment]
> > > Thanks @Kallirroi ! Can you try installing the git commit hook with `./gradlew addKtlintCheckGitPreCommitHook`?
> > 
> > 
> > Great, now it complains 😄
> 
> Cool, I'll add a comment about enabling this.

Done

**Comment by oxtoacart** [comment]
Thanks for the review @Kallirroi , merging

**Pull request merged**
